### ISSUE TITLE
作者您好，我在复现项目的时候，运行到step2的时候就遇到很多问题，想请您解答下！

### ISSUE THREAD

**Issue by HolicAnn** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#45]
Traceback (most recent call last):
  File "/mnt/c/Users/Alan/Desktop/TNSCUI2020-Seg-Rank1st-master/TNSCUI2020-Seg-Rank1st-master/step2to4_train_validate_inference/step2_TrainAndValidate.py", line 189, in <module>
    main(config)
  File "/mnt/c/Users/Alan/Desktop/TNSCUI2020-Seg-Rank1st-master/TNSCUI2020-Seg-Rank1st-master/step2to4_train_validate_inference/step2_TrainAndValidate.py", line 116, in main
    solver.train()
  File "/mnt/c/Users/Alan/Desktop/TNSCUI2020-Seg-Rank1st-master/TNSCUI2020-Seg-Rank1st-master/step2to4_train_validate_inference/tnscui_utils/solver.py", line 245, in train
    for i, sample in enumerate(self.train_loader):
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/mnt/c/Users/Alan/Desktop/TNSCUI2020-Seg-Rank1st-master/TNSCUI2020-Seg-Rank1st-master/step2to4_train_validate_inference/loader/data_loader.py", line 281, in __getitem__
    [image, GT] = data_aug(image, GT)
                  ^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Alan/Desktop/TNSCUI2020-Seg-Rank1st-master/TNSCUI2020-Seg-Rank1st-master/step2to4_train_validate_inference/loader/img_mask_aug.py", line 117, in data_aug
    images_aug = seq_det.augment_images(imgs)  # 进行增强
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/imgaug/augmenters/meta.py", line 822, in augment_images
    return self.augment_batch_(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/imgaug/augmenters/meta.py", line 641, in augment_batch_
    batch_inaug = self._augment_batch_(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/imgaug/augmenters/meta.py", line 3124, in _augment_batch_
    batch = self[index].augment_batch_(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/imgaug/augmenters/meta.py", line 641, in augment_batch_
    batch_inaug = self._augment_batch_(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/imgaug/augmenters/meta.py", line 3395, in _augment_batch_
    augmenter_active = self._get_augmenter_active(batch.nb_rows,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/imgaug/augmenters/meta.py", line 3368, in _get_augmenter_active
    augmenter_active = np.zeros((nb_rows, len(self)), dtype=np.bool)
                                                            ^^^^^^^
  File "/home/alan/miniforge3/envs/torch/lib/python3.11/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

ERROR conda.cli.main_run:execute(47): `conda run python /mnt/c/Users/Alan/Desktop/TNSCUI2020-Seg-Rank1st-master/TNSCUI2020-Seg-Rank1st-master/step2to4_train_validate_inference/step2_TrainAndValidate.py` failed. (See above for error)

进程已结束，退出代码为 1

**Comment by HolicAnn** [comment]
这个是我哪儿没有配置正确吗，我用的下载的DDIT数据集来做的

**Comment by HolicAnn** [comment]
找到了，这个问题解决了
